name: Build mxe

on:
  workflow_call:
    inputs:
      MXE_VERSION:
        required: true
        type: string
      GCC_VERSION:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Cache MXE
        id: cache-mxe
        uses: actions/cache@v4
        with:
          path: /opt/mxe
          key: ${{ runner.os }}-mxe-v${{ inputs.MXE_VERSION }}-gcc${{ inputs.GCC_VERSION }}
          # restore-keys: |
          #   ${{ runner.os }}-mxe-

      - name: Install MXE dependencies
        if: steps.cache-mxe.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y autopoint gperf intltool libtool-bin lzip

      - name: Remove Python 3 and set Python 2 as default
        if: steps.cache-mxe.outputs.cache-hit != 'true'
        run: |
          sudo apt-get remove -y python3
          sudo apt-get install -y python2
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
          sudo update-alternatives --set python /usr/bin/python2

      - name: Set up MXE environment (Windows XP support)
        if: steps.cache-mxe.outputs.cache-hit != 'true'
        run: |
          if [ ! -d /opt/mxe ]; then
            git clone https://github.com/mxe/mxe.git /opt/mxe
          fi
          cd /opt/mxe
          git checkout ${{ inputs.MXE_VERSION }}
          export MXE_PLUGIN_DIRS="$PWD/plugins/gcc${{ inputs.GCC_VERSION }}"
          make MXE_TARGETS=i686-w64-mingw32.static JOBS=$(nproc) gcc cmake sdl sdl_gfx sdl_mixer sdl_image yaml-cpp

      - name: Save MXE cache
        if: steps.cache-mxe.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: /opt/mxe
          key: ${{ runner.os }}-mxe-v${{ inputs.MXE_VERSION }}-gcc${{ inputs.GCC_VERSION }}

      # - name: Save MXE binaries artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: mxe-binaries
      #     path: /opt/mxe/usr

      # - name: Save MXE artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: mxe
      #     path: /opt/mxe