name: Build OXCE-XP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  # build-yaml-cpp:
  #   uses: ./.github/workflows/build-yaml-cpp.yml # This is how you call a reusable workflow
  #   with:
  #     YAML_CPP_VERSION: 0.6.3

  build-mxe:
    runs-on: ubuntu-22.04

    env:
      MXE_VERSION: 1efbfb68

    steps:
      - name: Cache MXE
        id: cache-mxe
        uses: actions/cache@v2
        with:
          path: /opt/mxe
          # key: ${{ runner.os }}-mxe-${{ hashFiles('**/mxe/**') }}
          key: ${{ runner.os }}-mxe-v${{ env.MXE_VERSION }}
          restore-keys: |
            ${{ runner.os }}-mxe-

      - name: Set up MXE environment (Windows XP support)
        if: steps.cache-mxe.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/mxe/mxe.git /opt/mxe
          cd /opt/mxe
          git checkout ${{ env.MXE_VERSION }}
          # git checkout 87a9b83dcf7d1650149e1d24f490d70405ddba1f  # Commit supporting XP
          make MXE_TARGETS=i686-w64-mingw32.static JOBS=$(nproc) gcc cmake sdl sdl_gfx sdl_mixer sdl_image yaml-cpp

      - name: Cache MXE
        id: cache-mxe
        uses: actions/cache@v4
        with:
          path: /opt/mxe
          # key: ${{ runner.os }}-mxe-${{ hashFiles('**/mxe/**') }}
          key: ${{ runner.os }}-mxe-v${{ env.MXE_VERSION }}
          restore-keys: |
            ${{ runner.os }}-mxe-
