name: Build OXCE-XP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  # build-yaml-cpp:
  #   uses: ./.github/workflows/build-yaml-cpp.yml
  #   with:
  #     YAML_CPP_VERSION: 0.6.3

  # build-mxe:
  #   uses: ./.github/workflows/build-mxe.yml
  #   with:
  #     MXE_VERSION: build-2022-01-13

  build-oxce:
    runs-on: ubuntu-22.04

    steps:
      - name: Build
        run: |
          git clone https://github.com/MeridianOXC/OpenXcom.git oxce
          cd oxce
          mkdir build
          cd build
          export PATH=/opt/mxe/usr/bin:$PATH
          /opt/mxe/usr/bin/x86_64-w64-mingw32.static-cmake -DCMAKE_BUILD_TYPE=Release -DDEV_BUILD=OFF -DBUILD_PACKAGE=OFF ..
          make -j$(nproc)
      - name: Setup tmate session
        if: always()
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30
