name: Build OXCE-XP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MXE_VERSION: build-2022-01-13
  GCC_VERSION: 9

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  # build-yaml-cpp:
  #   uses: ./.github/workflows/build-yaml-cpp.yml
  #   with:
  #     YAML_CPP_VERSION: 0.6.3

  build-mxe:
    uses: ./.github/workflows/build-mxe.yml
    with:
      MXE_VERSION: ${{ env.MXE_VERSION }}
      GCC_VERSION: ${{ env.GCC_VERSION }}

  build-oxce:
    runs-on: ubuntu-22.04
    needs:
      # - build-yaml-cpp
      - build-mxe

    steps:
      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y git cmake build-essential libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-gfx1.2-dev zlib1g-dev

      - name: Cache MXE
        id: cache-mxe
        uses: actions/cache@v4
        with:
          path: /opt/mxe
          key: ${{ runner.os }}-mxe-v${{ env.MXE_VERSION }}-gcc${{ env.GCC_VERSION }}
          restore-keys: |
            ${{ runner.os }}-mxe-

      - name: Check if cache was restored
        if: steps.cache-mxe.outputs.cache-hit != 'true'
        run: |
          echo "Cache not found. Failing the job."
          exit 1

      - name: Build
        run: |
          git clone https://github.com/MeridianOXC/OpenXcom.git oxce
          cd oxce
          # ln -s /opt/mxe/usr/i686-w64-mingw32.static/include/SDL deps/include
          # ln -s /opt/mxe/usr/i686-w64-mingw32.static/include/yaml-cpp deps/include
          ln -s /opt/mxe/usr/i686-w64-mingw32.static/include deps
          mkdir build
          cd build
          export PATH=/opt/mxe/usr/bin:$PATH
          /opt/mxe/usr/bin/i686-w64-mingw32.static-cmake -DCMAKE_BUILD_TYPE=Release -DDEV_BUILD=OFF -DBUILD_PACKAGE=OFF ..
          make -j$(nproc)

      - name: Setup tmate session
        if: always()
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30
