name: Build OXCE-XP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  # build-yaml-cpp:
  #   uses: ./.github/workflows/build-yaml-cpp.yml
  #   with:
  #     YAML_CPP_VERSION: 0.6.3

  build-mxe:
    uses: ./.github/workflows/build-mxe.yml
    with:
      MXE_VERSION: build-2022-01-13

  build-oxce:
    runs-on: ubuntu-22.04
    needs:
      # - build-yaml-cpp
      - build-mxe

    steps:
      # - name: Download MXE binaries artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: mxe-binaries
      #     path: /opt/mxe/usr

      # - name: Download MXE artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: mxe
      #     path: /opt/mxe

      - name: Cache MXE
        id: cache-mxe
        uses: actions/cache@v4
        with:
          path: /opt/mxe
          key: ${{ runner.os }}-mxe-vbuild-2022-01-13
          restore-keys: |
            ${{ runner.os }}-mxe-

      - name: Check if cache was restored
        if: steps.cache-mxe.outputs.cache-hit != 'true'
        run: |
          echo "Cache not found. Failing the job."
          exit 1

      - name: Build
        run: |
          git clone https://github.com/MeridianOXC/OpenXcom.git oxce
          cd oxce
          mkdir build
          cd build
          export PATH=/opt/mxe/usr/bin:$PATH
          /opt/mxe/usr/bin/i686-w64-mingw32.static-cmake -DCMAKE_BUILD_TYPE=Release -DDEV_BUILD=OFF -DBUILD_PACKAGE=OFF ..
          make -j$(nproc)

      - name: Setup tmate session
        if: always()
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30
